on: [push]

jobs:
  check_and_test:
    name: Check
    strategy:
      fail-fast: false
      matrix:
        backend: ["mysql"]
        os: [ubuntu-latest, macos-latest, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install mysql (Linux)
        if: runner.os == 'Linux' && matrix.backend == 'mysql'
        run: |
          mkdir -p /tmp/ssl
          bash mysql_ssl_rsa_setup.sh /tmp/ssl
          sudo systemctl start mysql.service
          mysql -e "CREATE user 'ssl'@'%' REQUIRE SSL;" -uroot -proot

      - name: Test mysql (Linux) connection
        if: runner.os == 'Linux' && matrix.backend == 'mysql'
        run: |
          mysql -uroot -proot -e "SELECT 1"
          mysql -ussl --ssl-ca=/tmp/ssl/ca.pem -e "SELECT 1"
          mysql -ussl --ssl-cert=/tmp/ssl/client-cert.pem --ssl-key=/tmp/ssl/client-key.pem -e "SELECT 1"

      - name: Install mysql (MacOS)
        if: runner.os == 'macOS' && matrix.backend == 'mysql'
        run: |
          brew install mariadb@10.5
          mkdir -p /tmp/ssl
          bash mysql_ssl_rsa_setup.sh /tmp/ssl
          /usr/local/opt/mariadb@10.5/bin/mysql.server start
          sleep 3
          /usr/local/opt/mariadb@10.5/bin/mysql -e "CREATE user 'ssl'@'%' REQUIRE SSL;" -urunner

      - name: Test mysql (MacOS) connection
        if: runner.os == 'macOS' && matrix.backend == 'mysql'
        run: |
          mysql -urunner -e "SELECT 1"
          mysql -ussl --ssl-ca=/tmp/ssl/ca.pem -e "SELECT 1"
          mysql -ussl --ssl-cert=/tmp/ssl/client-cert.pem --ssl-key=/tmp/ssl/client-key.pem -e "SELECT 1"

      - name: Install mysql (Windows) pre
        if: runner.os == 'Windows' && matrix.backend == 'mysql'
        shell: bash
        run: |
          ls -al
          bash mysql_ssl_rsa_setup.sh C:\Temp

      - name: Install mysql (Windows)
        if: runner.os == 'Windows' && matrix.backend == 'mysql'
        shell: cmd
        run: |
          choco install mysql
          "C:\tools\mysql\current\bin\mysql" -e "CREATE user 'ssl'@'%' REQUIRE SSL;" -uroot

      - name: Test mysql (Windows) connection
        if: runner.os == 'Windows' && matrix.backend == 'mysql'
        shell: cmd
        run: |
          "C:\tools\mysql\current\bin\mysql" -uroot -e "SELECT 1"
          "C:\tools\mysql\current\bin\mysql" -ussl --ssl-ca=C:\tools\mysql\current\lib -e "SELECT 1"
          "C:\tools\mysql\current\bin\mysql" -ussl --ssl-cert=/tmp/ssl/client-cert.pem --ssl-key=/tmp/ssl/client-key.pem -e "SELECT 1"
