on: [push]

jobs:
  check_and_test:
    name: Check
    strategy:
      fail-fast: false
      matrix:
        backend: ["mysql"]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-2019
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      # https://dev.mysql.com/doc/refman/5.7/en/option-files.html
      - name: Install mysql (Linux)
        if: runner.os == 'Linux' && matrix.backend == 'mysql'
        run: |
          pwd
          ls -al /etc/mysql/
          ls -al /etc/mysql/conf.d/
          ls -al /etc/mysql/mysql.conf.d/
          sudo cp mysql/ssl.cnf /etc/mysql/conf.d/
          sudo bash mysql/mysql_ssl_rsa_setup.sh /tmp/ssl
          #mysql_ssl_rsa_setup --verbose --uid=mysql --datadir=/tmp/ssl
          #sudo chown -R mysql:mysql /tmp/ssl
          ls -al /tmp/ssl
      - name: Up mysql (Linux)
        if: runner.os == 'Linux' && matrix.backend == 'mysql'
        run: |
          set +e
          sudo systemctl start mysql.service
          code=$?
          if [ $code -ne 0 ]; then
            journalctl -xeu mysql.service
            exit $code
          fi
          set -e
          mysql -uroot -proot -e "CREATE user 'ssl'@'%' REQUIRE SSL;"
      - name: Show mysql setting (Linux)
        if: runner.os == 'Linux' && matrix.backend == 'mysql'
        run: |
          mysql -uroot -proot -e "\\s"
          mysql -uroot -proot -e "SHOW VARIABLES LIKE '%ssl%';"
          mysql -uroot -proot -e "SHOW GLOBAL STATUS LIKE 'current_tls%';"
      - name: Test mysql connection (Linux)
        if: runner.os == 'Linux' && matrix.backend == 'mysql'
        run: |
          mysql -uroot -proot -e "SELECT 1"
          mysql -ussl --ssl-ca=/tmp/ssl/ca.pem -e "SELECT 2"
          mysql -ussl --ssl-cert=/tmp/ssl/client-cert.pem --ssl-key=/tmp/ssl/client-key.pem -e "SELECT 3"

      - name: Setup mysql (MacOS)
        if: runner.os == 'macOS' && matrix.backend == 'mysql'
        run: |
          bash mysql/mysql_ssl_rsa_setup.sh /tmp/ssl
          ls -al /tmp/ssl
      - name: Install mysql (MacOS)
        if: runner.os == 'macOS' && matrix.backend == 'mysql'
        run: |
          brew install mariadb@10.5
          ls -al $(brew --prefix mariadb@10.5)/
          ls -al $(brew --prefix mariadb@10.5)/conf.d/
          ls -al $(brew --prefix mariadb@10.5)/mysql.conf.d/
          cp mysql/ssl.cnf $(brew prefix mariadb@10.5)/conf.d
          $(brew --prefix mariadb@10.5)/bin/mysql.server start
          sleep 3
          $(brew --prefix mariadb@10.5)/bin/mysql -urunner -e "CREATE user 'ssl'@'%' REQUIRE SSL;"
      - name: Show mysql setting (macOS)
        if: runner.os == 'macOS' && matrix.backend == 'mysql'
        run: |
          $(brew --prefix mariadb@10.5)/bin/mysql -urunner -e "\\s"
          $(brew --prefix mariadb@10.5)/bin/mysql -urunner -e "SHOW VARIABLES LIKE '%ssl%';"
          $(brew --prefix mariadb@10.5)/bin/mysql -urunner -e "SHOW GLOBAL STATUS LIKE 'current_tls%';"
      - name: Test mysql connection (MacOS)
        if: runner.os == 'macOS' && matrix.backend == 'mysql'
        run: |
          $(brew --prefix mariadb@10.5)/bin/mysql -urunner -e "SELECT 1"
          $(brew --prefix mariadb@10.5)/bin/mysql -ussl --ssl-ca=/tmp/ssl/ca.pem -e "SELECT 1"
          $(brew --prefix mariadb@10.5)/bin/mysql -ussl --ssl-cert=/tmp/ssl/client-cert.pem --ssl-key=/tmp/ssl/client-key.pem -e "SELECT 1"

      - name: Setup mysql (Windows)
        if: runner.os == 'Windows' && matrix.backend == 'mysql'
        shell: bash
        env:
          MSYS_NO_PATHCONV: 1
        run: |
          bash mysql/mysql_ssl_rsa_setup.sh /c/Temp/ssl
          ls -al /c/Temp/ssl
      - name: Install mysql (Windows)
        if: runner.os == 'Windows' && matrix.backend == 'mysql'
        shell: cmd
        run: |
          choco install mysql
      - name: Install mysql 2 (Windows)
        if: runner.os == 'Windows' && matrix.backend == 'mysql'
        shell: bash
        run: |
          ls -al /c/tools/mysql/current
          cat /c/tools/mysql/current/my.ini
          cat mysql/ssl.win.cnf >> /c/tools/mysql/current/my.ini
          cat /c/tools/mysql/current/my.ini
          /c/tools/mysql/current/bin/mysql -uroot -e "CREATE user 'ssl'@'%' REQUIRE SSL;"
      - name: Show mysql setting (Windows)
        if: runner.os == 'Windows' && matrix.backend == 'mysql'
        shell: bash
        run: |
          /c/tools/mysql/current/bin/mysql -uroot -e "\\s"
          /c/tools/mysql/current/bin/mysql -uroot -e "SHOW VARIABLES LIKE '%ssl%';"
          /c/tools/mysql/current/bin/mysql -uroot -e "SHOW GLOBAL STATUS LIKE 'current_tls%';"
      - name: Test mysql connection (Windows)
        if: runner.os == 'Windows' && matrix.backend == 'mysql'
        shell: cmd
        run: |
          "C:\tools\mysql\current\bin\mysql" -uroot -e "SELECT 1"
          "C:\tools\mysql\current\bin\mysql" -ussl --ssl-ca=C:\Temp\ssl\ca.pem -e "SELECT 2"
          "C:\tools\mysql\current\bin\mysql" -ussl --ssl-cert=C:\Temp\ssl\client-cert.pem --ssl-key=C:\Temp\ssl\client-key.pem -e "SELECT 3"
